image: node:18

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
    - cp build/index.html build/404.html || true
  artifacts:
    paths:
      - build

deploy:
  stage: deploy
  image: alpine:latest
  needs: ["build"]
  before_script:
    - apk add --no-cache lftp
  script:
    - |
      lftp -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" <<EOF
      set ftp:ssl-allow no
      set ftp:passive-mode true
      echo '--- pwd ---'
      pwd
      echo '--- cd to $FTP_PATH ---'
      cd $FTP_PATH
      echo '--- ls before ---'
      cls -l
      # upload *contents* of build/ into public_html
      mirror -R --delete ${APP_DIR:-.}/build .
      echo '--- ls after ---'
      cls -l
      bye
      EOF
  only:
    - main



